/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API information */
        get: operations["getApiInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register an account */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh session */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the refresh session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's active organization memberships */
        get: operations["listOrganizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/membership": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        /** Get the authorized current membership */
        get: operations["getOrganizationMembership"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        /** List active Events in an organization */
        get: operations["listEvents"];
        put?: never;
        /** Create an Event */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        /** Get an Event */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        /** Archive an Event */
        delete: operations["archiveEvent"];
        options?: never;
        head?: never;
        /** Update mutable Event settings */
        patch: operations["updateEvent"];
        trace?: never;
    };
    "/organizations/{organizationId}/events/{eventId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        /** Get trusted Event photo processing counters */
        get: operations["getEventStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/events/{eventId}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        /** List active Photos in an Event */
        get: operations["listPhotos"];
        put?: never;
        /** Create a pending Photo owned by the authorized Event */
        post: operations["createPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/events/{eventId}/photos/{photoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                eventId: components["parameters"]["EventId"];
                photoId: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        /** Get a Photo status */
        get: operations["getPhoto"];
        put?: never;
        post?: never;
        /** Soft-delete a Photo */
        delete: operations["deletePhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/events/{eventId}/photos/{photoId}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                eventId: components["parameters"]["EventId"];
                photoId: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Requeue a failed Photo */
        post: operations["reprocessPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/events/{publicToken}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicToken: string;
            };
            cookie?: never;
        };
        /** Get an eligible public Event */
        get: operations["getPublicEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiInfo: {
            name: string;
            version: string;
        };
        Credentials: {
            /** Format: email */
            email: string;
            password: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: date-time */
            createdAt: string;
        };
        OrganizationMembership: {
            /** Format: uuid */
            organizationId: string;
            organizationName: string;
            /** @enum {string} */
            role: "owner" | "admin" | "editor" | "viewer";
        };
        /** @enum {string} */
        EventVisibility: "private" | "public";
        CreateEvent: {
            name: string;
            visibility: components["schemas"]["EventVisibility"];
            /** Format: date-time */
            expiresAt?: string | null;
            downloadsEnabled: boolean;
            /** @description Optional cosine-similarity policy override; no production default is approved. */
            matchThreshold?: number | null;
        };
        UpdateEvent: {
            name?: string;
            visibility?: components["schemas"]["EventVisibility"];
            /** Format: date-time */
            expiresAt?: string | null;
            downloadsEnabled?: boolean;
            /** @description Optional cosine-similarity policy override; no production default is approved. */
            matchThreshold?: number | null;
        };
        Event: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            name: string;
            visibility: components["schemas"]["EventVisibility"];
            /** @enum {string} */
            status: "active" | "archived";
            /** Format: date-time */
            expiresAt: string | null;
            downloadsEnabled: boolean;
            matchThreshold: number | null;
            /** Format: uuid */
            createdByUserId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PublicEvent: {
            name: string;
            /** Format: date-time */
            expiresAt: string | null;
            downloadsEnabled: boolean;
        };
        EventProcessingStatus: {
            /** Format: uuid */
            eventId: string;
            activeTotal: number;
            pending: number;
            uploading: number;
            uploaded: number;
            queued: number;
            processing: number;
            ready: number;
            failed: number;
            deleted: number;
        };
        /** @enum {string} */
        PhotoStatus: "pending" | "uploading" | "uploaded" | "queued" | "processing" | "ready" | "failed";
        CreatePhoto: {
            originalFilename: string;
            /** @enum {string} */
            contentType: "image/jpeg" | "image/png" | "image/webp";
            byteSize: number;
            checksumSha256?: string;
        };
        Photo: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            eventId: string;
            originalFilename: string;
            contentType: string;
            byteSize: number;
            status: components["schemas"]["PhotoStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AuthResponse: {
            accessToken: string;
            /** @constant */
            tokenType: "Bearer";
            expiresIn: number;
            user: components["schemas"]["User"];
        };
        Error: {
            code: string;
            message: string;
            traceId?: string;
        };
    };
    responses: {
        /** @description Authentication succeeded; the refresh token is set as an HttpOnly cookie. */
        AuthSuccess: {
            headers: {
                "Set-Cookie"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuthResponse"];
            };
        };
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication request rejected */
        AuthRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource was not found or is not available to the caller */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        OrganizationId: string;
        EventId: string;
        PhotoId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getApiInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiInfo"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            201: components["responses"]["AuthSuccess"];
            400: components["responses"]["BadRequest"];
            409: components["responses"]["AuthRejected"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            200: components["responses"]["AuthSuccess"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["AuthRejected"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AuthSuccess"];
            401: components["responses"]["AuthRejected"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["AuthRejected"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active organization memberships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMembership"][];
                };
            };
            401: components["responses"]["AuthRejected"];
        };
    };
    getOrganizationMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized organization membership */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMembership"];
                };
            };
            401: components["responses"]["AuthRejected"];
            404: components["responses"]["NotFound"];
        };
    };
    listEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active Events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            401: components["responses"]["AuthRejected"];
            404: components["responses"]["NotFound"];
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEvent"];
            };
        };
        responses: {
            /** @description Event created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["AuthRejected"];
            404: components["responses"]["NotFound"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            401: components["responses"]["AuthRejected"];
            404: components["responses"]["NotFound"];
        };
    };
    archiveEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthRejected"];
            404: components["responses"]["NotFound"];
        };
    };
    updateEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEvent"];
            };
        };
        responses: {
            /** @description Event updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["AuthRejected"];
            404: components["responses"]["NotFound"];
        };
    };
    getEventStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event processing counters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventProcessingStatus"];
                };
            };
            401: components["responses"]["AuthRejected"];
            404: components["responses"]["NotFound"];
        };
    };
    listPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active Photos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"][];
                };
            };
            401: components["responses"]["AuthRejected"];
            404: components["responses"]["NotFound"];
        };
    };
    createPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                eventId: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePhoto"];
            };
        };
        responses: {
            /** @description Pending Photo created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["AuthRejected"];
            404: components["responses"]["NotFound"];
        };
    };
    getPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                eventId: components["parameters"]["EventId"];
                photoId: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Photo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            401: components["responses"]["AuthRejected"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                eventId: components["parameters"]["EventId"];
                photoId: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Photo deleted or already deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthRejected"];
            404: components["responses"]["NotFound"];
        };
    };
    reprocessPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                eventId: components["parameters"]["EventId"];
                photoId: components["parameters"]["PhotoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Photo requeued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Photo"];
                };
            };
            401: components["responses"]["AuthRejected"];
            404: components["responses"]["NotFound"];
        };
    };
    getPublicEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicToken: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Limited public Event capability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEvent"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
